### PR TITLE
Milestone to fix errors achieved

### LINKED ISSUE #343: The yml workflow is giving errors
<h1>Error starting the game.</h1>

previously when you started a new game, it returned 0
but correctly it throws some errors.

> [!WARNING]\
> **Play Chess**
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-> python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### PR DESCRIPTION
**Pull request by Hezethegamer**
# Updates

made fixes to the yml file which had issues...

closes #343

### CODE REVIEW

**Review by rezzcode — COMMENTED** [review]
great improvements

**Comment by the1Riddle** [comment]
this will close #343

**Review by the1Riddle — APPROVED** [review]
LGTM

**Review by Hezethegamer — COMMENTED** [review]
updated the yml file...

**Pull request merged**
